---
title: "Core genes Venn Diagrams"
output: html_notebook
---

Read in data, set wd, load packages
```{r, message=FALSE}
library(scater)
library(plotly)
library(pheatmap)
library(Rtsne)
library(viridis)
library(VennDiagram)
setwd("/Users/vh3/Documents/MCA/ANALYSIS_3")
rawmca <- readRDS("MCAqcTMMSLS34_20181026.rds")
```



From the raw data, How many cells are expressed in more than 80% of cells, in less than 5 cells? 
```{r}
head(rowData(rawmca))
allrowdata <- rowData(rawmca)
numcells <- dim(colData(rawmca))[1]
numcells

allrowdata$core <- allrowdata$n_cells_counts/numcells
allrowdata$corebin <- "FALSE"
allrowdata$corebin[allrowdata$core >= 0.8 ] <- "TRUE"
table(allrowdata$corebin)

suball <- allrowdata[which(allrowdata$corebin == "TRUE"), ]
coregenes <- suball$feature_symbol
#write.csv(coregenes, "coregenes0.8.csv")

lessthan5cell <- droplevels(subset(allrowdata, n_cells_counts <= 5))
dim(lessthan5cell)
lt5 <- lessthan5cell$feature_symbol
#write.csv(lt5, "expinlessthan5cells.csv")
```

Sep each category. Shz and trophs are together since there are only 22 trophs. Trophs are then the limiting stage with only 67
```{r}

pheno <- as.data.frame(colData(rawmca))
library(plyr)
test <- ddply(pheno,.(ShortenedLifeStage4),function(x) x[sample(nrow(x),60),])

cells <- test$sample_id

datalist = list()

for (i in unique(pheno$ShortenedLifeStage4)) {
   stage <- rawmca[, rawmca$ShortenedLifeStage4==i]
   substage <- stage[, stage$sample_id %in% cells]
  counts <- as.data.frame(counts(substage))
  Ooc <- apply(counts, MARGIN = 1, function(x) sum(x > 0))
  Ooc <- as.data.frame(Ooc)
  cores <- droplevels(subset(Ooc, Ooc >= 30))
  length(cores$Ooc)
  Ooccore <- as.data.frame(rownames(cores))
  colnames(Ooccore) <- "gene"
  Ooccore$stage <- rep(i, length(Ooccore$gene))
  #dat <- data.frame(i, j, length(overlap), HVGnotpir, notHVGnotpir, notHVGyespir, test$p.value)
     #colnames(dat) <- c("Clust", "Core", "overlap", "clustnotcore", "neither", "notclustyescore", "pval")
     datalist[[i]] <- Ooccore
     
}
big_data = do.call(rbind, datalist)


datalist2 = list()
for (i in unique(big_data$stage)) {
  getit <- datalist[[i]]
  genes <- getit$gene
  allbut <- droplevels(subset(big_data, stage != i))
  allbutgenes <- allbut$gene
  unique <- as.data.frame(setdiff(genes, allbutgenes))
  colnames(unique) <- "unique"
  unique$stage <- rep(i, length(unique$unique))
  datalist2[[i]] <- unique
}

coreunique <- do.call(rbind, datalist2)
write.csv(big_data, "CorebyStage_20190111.csv")
write.csv(coreunique, "CoreUniquebyStage_20190111.csv")

```


```{r}


```
```{r}
mscs <- read.csv("Gene_pheno_manknn5_4_k20_20180814.csv", header=TRUE, row.names = 1)

Stageunique <- droplevels(subset(coreunique, stage == "Spz"))
Stageunique$Stageuni <- rep(TRUE, length(Stageunique$unique))

all <- merge(mscs, Stageunique, by.x="gene_id", by.y="unique", all.x=TRUE, all.y=FALSE)

all$stageuni2 <- rep("no", length(all$gene_id))
all[which(all$Stageuni == "TRUE"), ]$stageuni2 <- "yes"

no <- droplevels(subset(all, stageuni2=="no"))
yes <- droplevels(subset(all, stageuni2=="yes"))

ggplot(no, aes(X, Y)) + 
  geom_point(colour="grey88", size = 0.5) + 
  theme_classic() +
  geom_point(data = yes, aes(X, Y), colour="red", size=0.8) +
  labs(x="Dimension 1", y="Dimension 2", title="Sporozoite") +
  theme(axis.title=element_text(size=10), axis.text.x = element_blank(), axis.text.y = element_blank(), plot.title = element_text(hjust = 0.5, size=12))


clusters <- read.csv("Table_S2_ClusterAssignments_20180814.csv", header=TRUE)



datalist = list()
  
 for (i in unique(clusters$Cluster_Name)) {
   clust <- clusters[clusters$Cluster_Name==i, ]
   for (j in colnames(coreunique$stage)) {
     stagecore <- coreunique[[j]]
     overlap <- intersect(clust$gene_id, stagecore$unique)
     HVGnotpir <- length(clust$gene_id) - length(overlap)
     notHVGnotpir <- length(clusters$gene_id) - length(stagecore$unique) - length(clust$gene_id)
     notHVGyespir <- length(clust$gene_id) - length(overlap)
     
     B <- matrix(c(HVGnotpir, notHVGnotpir, length(overlap), notHVGyespir), nrow=2, ncol=2)
     
     test <- chisq.test(B)
     dat <- data.frame(i, j, length(overlap), HVGnotpir, notHVGnotpir, notHVGyespir, test$p.value)
     colnames(dat) <- c("Clust", "Core", "overlap", "clustnotcore", "neither", "notclustyescore", "pval")
     datalist[[j]] <- dat
     
   }
}

   datalist = list()
   
   for (i in unique(clusters$Cluster_Name)) {
     clust <- clusters[clusters$Cluster_Name==i, ]
     for (j in unique(coreunique$stage)) {
       stagecore <- coreunique[coreunique$stage==j,]
       overlap <- intersect(clust$gene_id, stagecore$unique)
       HVGnotpir <- length(clust$gene_id) - length(overlap)
       notHVGnotpir <- length(clusters$gene_id) - length(stagecore$unique) - length(clust$gene_id)
       notHVGyespir <- length(clust$gene_id) - length(overlap)
       
       B <- matrix(c(HVGnotpir, notHVGnotpir, length(overlap), notHVGyespir), nrow=2, ncol=2)
       
       test <- fisher.test(B, alternative = "less")
       dat <- data.frame(i, j, length(overlap), HVGnotpir, notHVGnotpir, notHVGyespir, test$p.value)
       colnames(dat) <- c("Clust", "Core", "overlap", "clustnotcore", "neither", "notclustyescore", "pval")
       dat$adjpval <- p.adjust(dat$pval, method = "bonferroni", n = length(dat$pval))
       datalist[[j]] <- dat
       
     }
   big_data = do.call(rbind, datalist)
   #write.csv(big_data, file=paste0("bigdatachi_", i, ".csv", sep=""))
   write.table(big_data, file="bd2.csv", append=TRUE, sep=",")
 }
 big_data = do.call(rbind, datalist)
 
 

```

